name: Debug log
on: push
jobs:
  log:
    runs-on: ubuntu-latest
    steps:
    - run: gh variable set ACTIONS_STEP_DEBUG true
    - run: echo "::debug::This is a debug log"
    - run: gh variable delete ACTIONS_STEP_DEBUG