name: Fail-fast matrix
on: push
jobs:
  run:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        time: [10, 20, 30]
    steps:
    - run: sleep "${SLEEP_TIME}" && exit 1
      continue-on-error: true # Continue on error to run all matrix jobs
      env:
        SLEEP_TIME: ${{ matrix.time }}