name: Hash functions
on: push
jobs:
  hash:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - run: echo "${HASH}"
      env:
        HASH: ${{ hashFiles('.github/workflows/*.yml') }}
